jquery_lang_js.prototype.lang.fr = {
	'Choose the options below then submit, and you will get your own unique password instantly generated by our script. All random passwords generated by this software are available on your local computer only. No passwords are transferred over the Internet. No personal data is stored by or captured through the site.': 'Choisissez les options ci-dessous puis validez, vous obtiendrez un mot de passe g&eacute;n&eacute;r&eacute; instantan&eacute;ment par notre logiciel. Tous les mots de passe g&eacute;n&eacute;r&eacute; par cette application sont al&eacute;atoires et disponibles uniquement sur votre ordinateur. Aucun mot de passe n\'est transf&eacute;r&eacute; &agrave; travers Internet. Aucune information personnelle n\'est collect&eacute;e ou stock&eacute;e sur ce site.',
	'You will always find the latest source code version of this script in our GitHub repository. You can check out the source code :': 'θα βρείτε πάντα τη τελευταία έκδοση του πηγαίου κώδικα στο αποθετήριο μας. Μπορείτε να το κατεβάσετε από τη διεύθυνση :',
	'Powered by Clicface': 'Ανάπτυξη από την Clicface',
	'password character length': 'μέγεθος χαρακτήρων κωδικού',
	'string letters': 'μικρά γράμματα',
	'capital letters': 'κεφαλαία γράμματα',
	'digits': 'ψηφία',
	'special symbols': 'ειδκοί χαρακτήρες',
	'ambiguous characters': 'περίεργοι χαρακτήρες',
	'Generate Password': 'δημιουργία κωδικουύ',
	'Please make at least one selection': 'κάντε τουλάχιστον μία επιλογή',
}
