jquery_lang_js.prototype.lang.el = {
	'Choose the options below then submit, and you will get your own unique password instantly generated by our script. All random passwords generated by this software are available on your local computer only. No passwords are transferred over the Internet. No personal data is stored by or captured through the site.': 'επιλέξτε παρακάτω και θα λάβετε το δικό σας μοναδικό κωδικό άμεσα δημιουργημένο από το πρόγραμμα. όλοι οι τυχαίοι κωδικοί που δημιουργούνται από αυτό το λογισμικό είναι διαθέσιμοι στο προσωπικό σας υπολογιστή μόνο. δεν μεταφέρονται κωδικοί στο διαδίκτυο. προσωπικά δεδομένα δεν αποθηκεύονται στη σελίδα.'
	'You will always find the latest source code version of this script in our GitHub repository. You can check out the source code ': 'θα βρείτε πάντα τη τελευταία έκδοση του πηγαίου κώδικα στο αποθετήριο μας. Μπορείτε να το κατεβάσετε από τη διεύθυνση ',
	'Powered by Clicface': 'Ανάπτυξη από την Clicface',
	'password character length': 'μέγεθος χαρακτήρων κωδικού',
	'string letters': 'μικρά γράμματα',
	'capital letters': 'κεφαλαία γράμματα',
	'digits': 'ψηφία',
	'special symbols': 'ειδκοί χαρακτήρες',
	'ambiguous characters': 'περίεργοι χαρακτήρες',
	'Generate Password': 'δημιουργία κωδικουύ',
	'Please make at least one selection': 'κάντε τουλάχιστον μία επιλογή',
}
